version: "3.7"
services:
    appbackend:
        build: backend/
        ports: 
          - 5432:5432
          - 8080:8080
        volumes:
          - ${APP_POSTGRES_DIR}:/var/lib/postgresql
          - ../backend/target:/srv:ro
    proxy:
        build: nginx/
        depends_on:
          - appbackend
        links:
          - appbackend
        ports: 
          - 80:80
        volumes:
          - ../ui/dist:/usr/share/nginx/html:ro
